services:
  - type: web
    name: leadly-ew8k
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    preDeployCommand: python manage.py migrate --noinput
    startCommand: python manage.py migrate --noinput && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.9
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: leadly-ew8k.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://leadly-ew8k.onrender.com
      - key: SITE_DOMAIN
        value: leadly-ew8k.onrender.com
      - key: SITE_NAME
        value: Leadly
      - key: SECRET_KEY
        generateValue: true